### ISSUE TITLE
ASIC 0.8V VDDIO pins are not connected to supply

### ISSUE THREAD

**Issue by skot** [benjamin-wilson/NerdNOS#2]
The net names on the supply and pins don't match. 
<img width="503" alt="image" src="https://github.com/benjamin-wilson/NerdNOS/assets/140785/05ca7fb0-e106-433f-98c6-ad8097f6dfa7">
<img width="401" alt="image" src="https://github.com/benjamin-wilson/NerdNOS/assets/140785/db019c62-9558-451d-95cc-778112a84600">

**Comment by benjamin-wilson** [comment]
Fixed, second 1v8 was also not connected
